# Generated by Django 6.1.1 on 2026-09-04 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_id', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invocador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=100, unique=True)),
                ('riot_id', models.CharField(max_length=100)),
                ('game_name', models.CharField(max_length=50)),
                ('tag_line', models.CharField(max_length=10)),
                ('summoner_level', models.IntegerField(default=0)),
                ('profile_icon_id', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateTimeField()),
                ('duracion_segundos', models.IntegerField()),
                ('modo_juego', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_type', models.CharField(max_length=30)),
                ('tier', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=5)),
                ('league_points', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('invocador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligas', to='stats.invocador')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('win', models.BooleanField(default=False)),
                ('team_id', models.IntegerField()),
                ('campeon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.campeon')),
                ('invocador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='stats.invocador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='stats.partida')),
            ],
            options={
                'unique_together': {('partida', 'invocador')},
            },
        ),
    ]
