# Generated by Django 6.1.1 on 2026-09-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='cs_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='doble_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='item0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='item1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='item2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='item3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='item4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='item5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='item6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='penta_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='quadra_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='runa_principal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='runa_secundaria',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='summoner1_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='summoner2_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='triple_kills',
            field=models.IntegerField(default=0),
        ),
    ]
