# Generated by Django 6.1.1 on 2026-09-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_participante_cs_total_participante_doble_kills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='role',
            field=models.CharField(default='', max_length=20),
        ),
    ]
