# Generated by Django 6.1.1 on 2026-09-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_participante_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='queue_id',
            field=models.IntegerField(default=0),
        ),
    ]
