# Generated by Django 6.1.1 on 2026-09-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_participante_queue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='queue_id',
            field=models.IntegerField(default=0),
        ),
    ]
