# Generated by Django 6.1.1 on 2026-09-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_participante_lp_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='damage_to_champions',
            field=models.IntegerField(default=0),
        ),
    ]
