# Generated by Django 6.1.1 on 2026-09-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_participante_damage_to_champions'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='gold_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='wards_destroyed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='wards_placed',
            field=models.IntegerField(default=0),
        ),
    ]
